services:
  frontend:
    image: registry.fauzi.studentdumbways.my.id/fe-dumbmerch:staging
    container_name: fe-staging
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
