services:
  frontend:
    image: registry.fauzi.studentdumbways.my.id/fe-dumbmerch:production
    container_name: fe-production
    restart: always
    ports:
      - "3001:80"
    env_file:
      - .env
