name: CI/CD Production FE
on:
  push:
    branches:
      - production
jobs:
  sonarqube:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: SonarQube scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=fe-dumbmerch-production

  build:
    runs-on: self-hosted
    needs: sonarqube
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          echo "REACT_APP_BASEURL=${{ secrets.REACT_APP_BASEURL_PRODUCTION }}" > .env
      - name: Login to Docker Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/fe-dumbmerch:production .
      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_REGISTRY }}/fe-dumbmerch:production
          format: table
          exit-code: 0
      - name: Push image to registry
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/fe-dumbmerch:production

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy
        run: |
          cd /home/fauzi/fe-production
          docker compose pull
          docker compose up -d --force-recreate

  test:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Test app with wget spider
        run: |
          wget --spider https://fauzi.studentdumbways.my.id || true
